name = "ai-r2-asset-binding"
compatibility_date = "2025-02-04"
compatibility_flags = [ "nodejs_compat" ]

# [vars]
# MY_VAR = "my-variable"

# Workers Logs
# Docs: https://developers.cloudflare.com/workers/observability/logs/workers-logs/
# Configuration: https://developers.cloudflare.com/workers/observability/logs/workers-logs/#enable-workers-logs
[observability]
enabled = true

[assets]
directory = "gentle-response-hub/dist"

[[r2_buckets]]
bucket_name = "www"
binding = "BUCKET"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"



 [ai]
 binding = "AI"
